### Creates a new patient entity
POST http://lb-b72b9500.elb.localhost.localstack.cloud:4566/api/patients
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Odogwu Marcel kafkatest",
  "email": "ukejemarcelkafkatest@gmail.com",
  "address": "29 Ezinifite Street",
  "dateOfBirth": "2003-04-02",
  "registeredDate": "2026-07-13"
}
